# This is a GitLab CI configuration to build the project as a docker image
# The file is generic enough to be dropped in a project containing a working Dockerfile
# Author: Florent CHAUVEAU <florent.chauveau@gmail.com>
# Mentioned here: https://blog.callr.tech/building-docker-images-with-gitlab-ci-best-practices/

# do not use "latest" here, if you want this to work in the future
image: docker:latest

variables:
  NODE_VERSION: 16-alpine

stages:
  - test
  - build
  - deploy

.remote_docker:
  variables:
    DOCKER_HOST: ssh://root@$DESTINATION_HOST
    PROJECT_NAME: ekorre # This should not contain any special chars
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -t rsa $DESTINATION_HOST >> ~/.ssh/known_hosts

docker build:
  # Use the official docker image.
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  # Default branch leaves tag empty (= latest tag)
  # All other branches are tagged with the escaped branch name (commit ref slug)
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - docker build --build-arg "NODE_VERSION=$NODE_VERSION" --pull -t "$CI_REGISTRY_IMAGE${tag}" .
    - docker push "$CI_REGISTRY_IMAGE${tag}"
    - docker image prune -af --filter "until=48h"
  # Run this job in a branch where a Dockerfile exists
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile
lint:
  stage: test
  image: "node:$NODE_VERSION"
  # Make sure docker info is not run and get some node info
  before_script:
    - apk update
    - apk add python3
    - node --version
    - npm ci --cache .npm --prefer-offline
  script:
    - npx eslint src
    - npx eslint test
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .npm/

tests:
  stage: test
  # Must be run on docker runner
  tags:
    - docker
  image:
    name: "node:$NODE_VERSION"
  before_script:
    - node --version
    - npm ci --cache .npm --prefer-offline
  script:
    - apk update
    - apk add bash sqlite python3
    - ./test/utils/setup-env.sh
    - npm run test:prebuild
    - ./test/utils/test-server-startup.sh
    - npm run test:regression
  artifacts:
    paths:
      - coverage
    expire_in: 1 week
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .npm/

deploy image:
  variables:
    DEPLOY_URL: "ekorre.esek.se"
  stage: deploy
  extends: .remote_docker
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest
    
    # Remove old container
    - docker stop $PROJECT_NAME 2> /dev/null || true
    - docker rm --force $PROJECT_NAME 2> /dev/null || true
    - docker image prune -f --filter "label=project=$PROJECT_NAME"
    
    - docker run
      --name $PROJECT_NAME
      --env ALLOWED_ORIGINS=https://efterphest.esek.se
      --env COOKIE_DOMAIN=esek.se
      --label "traefik.http.routers.$PROJECT_NAME.rule=Host(\`$DEPLOY_URL\`)"
      -d $CI_REGISTRY_IMAGE:latest
  environment:
    name: production
    url: $DEPLOY_URL
  only:
    - main
  needs: ['docker build', 'tests']
