# Needs docker v2 since COMPOSE_PROJECT_NAME is not available in v1
version: '3.9'

networks:
  traefik:
    external: true

services:
  ekorre:
    image: $IMAGE_NAME
    environment:
      - DB_HOST=postgres://postgres:example@postgres:5432/ekorre_ci
      - NODE_ENV=development
    networks:
      - traefik
      - default # to join compose network
    labels:
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-ekorre.rule=Host(`$DEPLOY_URL`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-ekorre.middlewares=cors@file"

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: ekorre_ci
