version: '3.6'

networks:
  traefik:
    external: true

volumes:
  ekorre_postgres:

services:
  postgres:
    image: postgres:alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ekorre_postgres:/data/postgres
    ports: [ 5432:5432 ]
    restart: unless-stopped
    